Issue2/create a register page
OpenSRP/opensrp-client-pnc pull request #10
Opened 2020-05-22 11:44 UTC by hmakandi

Creating a PR

2020-05-26 06:06 UTC, bennsimon requested changes

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/assets/config/maternity-profile-overview.yml
> +---
This file can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/assets/config/maternity-visit-row.yml
> +---
This file can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/assets/json.form/maternity_close.json
> +{
This file can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/assets/rule/maternity/outcome_relevance_rules.yml
> +---
This file can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/assets/rule/maternity/registration_calculation_rules.yml
> +---
Rename this file's directory

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/assets/rule/maternity/registration_constraint_rules.yml
> +name: step2_parity
Rename this file's directory

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/assets/rule/maternity/registration_relevance_rules.yml
> +---
Rename this file's directory

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/PncLibrary.java
> +    public String maternityLookUpQuery() {
This method can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/PncLibrary.java
> +    }
This methods can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncFormActivity.java
> +                dialog.show();
This can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncFormActivity.java
> +    }
This can be renamed correctly e.g `maternityOutcomeForm -> paternityOutcomeForm` or removed for now

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +                    removeOngoingTask(ongoingTask);
These can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +public class BasePncProfileActivity extends BaseProfileActivity implements PncProfileActivityContract.View {
Kindly rename any occurrences of maternity in this file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +        inflater.inflate(R.menu.menu_maternity_profile_activity, menu);
rename here

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +        super.setContentView(R.layout.maternity_activity_base_profile);
rename layout file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +            if (PncConstants.RegisterType.MATERNITY.equalsIgnoreCase(register_type)) {
use the correct register type

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncRegisterActivity.java
> +        }
update the message of the exception

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/adapter/ClientLookUpListAdapter.java
> +public class ClientLookUpListAdapter extends RecyclerView.Adapter<ClientLookUpListAdapter.MyViewHolder> {
rename any references to maternity in this file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/adapter/PncProfileVisitsAdapter.java
> +        View view = mInflater.inflate(R.layout.maternity_profile_overview_row, parent, false);
rename file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncConfiguration.java
> +public class PncConfiguration {
Rename any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncFormProcessingTask.java
> +    void processMaternityForm(@NonNull String eventType, String jsonString, @Nullable Intent data);
rename method

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncRegisterRowOptions.java
> +     * @param maternityRegisterViewHolder    The recycler view holder which holds the required views
update java docs

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncRegisterSwitcher.java
> +    void switchFromMaternityRegister(@NonNull CommonPersonObjectClient client, @NonNull Context context);
rename method

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/contract/PncProfileActivityContract.java
> +    interface Presenter extends BaseProfileContract.Presenter {
rename any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/contract/PncProfileActivityContract.java
> +        void saveMaternityCloseForm(@NonNull String eventType, @Nullable Intent data);
remove this

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/contract/PncRegisterActivityContract.java
> +        void fetchSavedMaternityOutcomeForm(@NonNull String baseEntityId, @Nullable String entityTable, @NonNull InteractorCallBack interactorCallBack);
remove this

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/dao/PncOutcomeFormDao.java
> +public interface PncOutcomeFormDao extends PncGenericDao<PncOutcomeForm> {
remove this file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/domain/YamlConfig.java
> +    private String test_results;
update this to proper variable naming convention

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +        PncMetadata maternityMetadata = PncLibrary.getInstance().getPncConfiguration().getMaternityMetadata();
Rename any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +                && !maternityMetadata.isFormWizardValidateRequiredFieldsBefore()) {
remove any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +        Intent intent = new Intent(getActivity(), PncLibrary.getInstance().getPncConfiguration().getMaternityMetadata().getProfileActivity());
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +            BasePncFormActivity maternityFormActivity = (BasePncFormActivity) activity;
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +    private PncRegisterQueryProviderContract maternityRegisterQueryProvider;
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +        maternityRegisterQueryProvider = ConfigurationInstancesHelper.newInstance(PncLibrary.getInstance().getPncConfiguration().getMaternityRegisterQueryProvider());
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +        return R.string.maternity_register_title_name;
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +                String sql = maternityRegisterQueryProvider.getObjectIdsQuery(filters, mainCondition);
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +                query = maternityRegisterQueryProvider.mainSelectWhereIDsIn();
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +            for (String sql : maternityRegisterQueryProvider.countExecuteQueries(filters, mainCondition)) {
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/holder/PncRegisterViewHolder.java
> +        firstDotDivider = itemView.findViewById(R.id.tv_maternityRegisterListRow_firstDotDivider);
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/interactor/BasePncRegisterActivityInteractor.java
> +    }
this can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/interactor/BasePncRegisterActivityInteractor.java
> +    public void saveRegistration(List<PncEventClient> maternityEventClientList, String jsonString, RegisterParams registerParams, PncRegisterActivityContract.InteractorCallBack callBack) {
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/interactor/PncProfileInteractor.java
> +    private void saveRegistration(@NonNull PncEventClient maternityEventClient, @NonNull String jsonString
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/listener/LookUpTextWatcher.java
> +            BasePncFormFragment maternityFormFragment = (BasePncFormFragment) jsonFormFragment;
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/model/PncProfileOverviewFragmentModel.java
> +                });
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/model/PncRegisterActivityModel.java
> +        List<PncEventClient> maternityEventClientList = new ArrayList<>();
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/pojo/PncMetadata.java
> +    private String maternityRegistrationFormName;
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/BasePncRegisterActivityPresenter.java
> +        }
This is not required

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +            }
this can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +            }
these can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +            PncEventClient maternityEventClient = processRegistration(jsonString, registerParams.getFormTag());
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +        PncEventClient maternityEventClient = PncJsonFormUtils.processMaternityRegistrationForm(jsonString, formTag);
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileOverviewFragmentPresenter.java
> +    private PncProfileOverviewFragmentModel model;
update any references to maternity in this file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncRegisterFragmentPresenter.java
> +        getView().initializeQueryParams("ec_client", null, null);
use table in `PncMetadata` class

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/processor/PncMiniClientProcessorForJava.java
> +            eventTypes.add(PncConstants.EventTypeConstants.MATERNITY_CLOSE);
these can be updated

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/processor/PncMiniClientProcessorForJava.java
> +        }
these can be updated or removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/provider/PncRegisterProvider.java
> +    private final LayoutInflater inflater;
update any references to maternity in this file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncDetailsRepository.java
> +    public ContentValues createValuesFor(@NonNull PncBaseDetails maternityDetails) {
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncDetailsRepository.java
> +    public boolean saveOrUpdate(@NonNull PncBaseDetails maternityDetails) {
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncDetailsRepository.java
> +    public PncBaseDetails findOne(@NonNull PncBaseDetails maternityDetails) {
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncOutcomeDetailsRepository.java
> +public class PncOutcomeDetailsRepository extends PncDetailsRepository {
this file can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncOutcomeFormRepository.java
> +public class PncOutcomeFormRepository extends BaseRepository implements PncOutcomeFormDao {
This file can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncRegistrationDetailsRepository.java
> +public class PncRegistrationDetailsRepository extends PncDetailsRepository {
Not needed can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/FilePath.java
> +        String MATERNITY_VISIT_ROW = "maternity-visit-row.yml";
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncConstants.java
> +        String MATERNITY = "maternity";
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncDbConstants.java
> +        }
Not required, can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncDbConstants.java
> +        String MATERNITY_OUTCOME_FORM = "maternity_outcome_form";
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncEventUtils.java
> +    public PncEventUtils(AppExecutors appExecutors) {
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncEventUtils.java
> +            maternityLibrary.getClientProcessorForJava().processClient(maternityLibrary.getEcSyncHelper().getEvents(lastSyncDate, BaseRepository.TYPE_Unprocessed));
update any references to maternity

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncJsonFormUtils.java
> +
update any references to maternity in this file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/res/layout/dosage_and_duration_layout.xml
> +<?xml version="1.0" encoding="utf-8"?>
The file can be removed

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/res/drawable/outcome_btn_overview_bg.xml
> +<?xml version="1.0" encoding="utf-8"?>
rename or remove file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/res/drawable/maternity_outcome_bg.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
rename or remove file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/res/drawable/maternity_btn_overview_normal.xml
> +<shape
rename or remove file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/res/drawable/maternity_btn_overview_clicked.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
rename or remove file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/res/drawable/diagnose_treat_bg.xml
> +<selector xmlns:android="http://schemas.android.com/apk/res/android">
rename or remove file

2020-05-26 06:06 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/PncProfileOverviewFragment.java
> +        View view =  inflater.inflate(R.layout.maternity_fragment_profile_overview, container, false);
update any references to maternity

2020-05-27 08:17 UTC, bennsimon commented
Update any reference to maternity

2020-05-28 07:02 UTC, syedowaisali90 commented on opensrp-pnc/src/main/assets/config/maternity-profile-overview.yml
> +---
File removed.

2020-05-28 07:02 UTC, syedowaisali90 commented on opensrp-pnc/src/main/assets/config/maternity-visit-row.yml
> +---
File removed.

2020-05-28 07:03 UTC, syedowaisali90 commented on opensrp-pnc/src/main/assets/json.form/maternity_close.json
> +{
file removed.

2020-05-28 07:05 UTC, syedowaisali90 commented on opensrp-pnc/src/main/assets/rule/maternity/registration_calculation_rules.yml
> +---
Done

2020-05-28 07:08 UTC, syedowaisali90 commented on opensrp-pnc/src/main/assets/rule/maternity/registration_constraint_rules.yml
> +name: step2_parity
Done

2020-05-28 07:08 UTC, syedowaisali90 commented on opensrp-pnc/src/main/assets/rule/maternity/registration_relevance_rules.yml
> +---
Done

2020-05-28 07:20 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/PncLibrary.java
> +    public String maternityLookUpQuery() {
Removed.

2020-05-28 07:22 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/PncLibrary.java
> +    }
Done

2020-05-28 07:24 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncFormActivity.java
> +                dialog.show();
Done

2020-05-28 07:26 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncFormActivity.java
> +    }
Removed for now.

2020-05-28 07:27 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +                    removeOngoingTask(ongoingTask);
Removed.

2020-05-28 08:42 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +public class BasePncProfileActivity extends BaseProfileActivity implements PncProfileActivityContract.View {
change to `maternity` to `pnc`

2020-05-28 08:43 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +        inflater.inflate(R.menu.menu_maternity_profile_activity, menu);
done

2020-05-28 08:43 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +        super.setContentView(R.layout.maternity_activity_base_profile);
done

2020-05-28 08:43 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncProfileActivity.java
> +            if (PncConstants.RegisterType.MATERNITY.equalsIgnoreCase(register_type)) {
done

2020-05-28 08:44 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncRegisterActivity.java
> +        }
done

2020-05-28 08:45 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/adapter/ClientLookUpListAdapter.java
> +public class ClientLookUpListAdapter extends RecyclerView.Adapter<ClientLookUpListAdapter.MyViewHolder> {
done

2020-05-28 08:48 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/adapter/PncProfileVisitsAdapter.java
> +        View view = mInflater.inflate(R.layout.maternity_profile_overview_row, parent, false);
done

2020-05-28 08:51 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncConfiguration.java
> +public class PncConfiguration {
done

2020-05-28 08:54 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncFormProcessingTask.java
> +    void processMaternityForm(@NonNull String eventType, String jsonString, @Nullable Intent data);
done

2020-05-28 09:00 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncRegisterRowOptions.java
> +     * @param maternityRegisterViewHolder    The recycler view holder which holds the required views
done

2020-05-28 09:01 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/config/PncRegisterSwitcher.java
> +    void switchFromMaternityRegister(@NonNull CommonPersonObjectClient client, @NonNull Context context);
done

2020-05-28 09:03 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/contract/PncProfileActivityContract.java
> +    interface Presenter extends BaseProfileContract.Presenter {
done

2020-05-28 09:08 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/contract/PncProfileActivityContract.java
> +        void saveMaternityCloseForm(@NonNull String eventType, @Nullable Intent data);
done

2020-05-28 09:15 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/contract/PncRegisterActivityContract.java
> +        void fetchSavedMaternityOutcomeForm(@NonNull String baseEntityId, @Nullable String entityTable, @NonNull InteractorCallBack interactorCallBack);
done

2020-05-28 09:18 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/dao/PncOutcomeFormDao.java
> +public interface PncOutcomeFormDao extends PncGenericDao<PncOutcomeForm> {
done

2020-05-28 09:19 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/domain/YamlConfig.java
> +    private String test_results;
done

2020-05-28 09:20 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +        PncMetadata maternityMetadata = PncLibrary.getInstance().getPncConfiguration().getMaternityMetadata();
done

2020-05-28 09:20 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +                && !maternityMetadata.isFormWizardValidateRequiredFieldsBefore()) {
done

2020-05-28 09:21 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +        Intent intent = new Intent(getActivity(), PncLibrary.getInstance().getPncConfiguration().getMaternityMetadata().getProfileActivity());
done

2020-05-28 09:21 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncFormFragment.java
> +            BasePncFormActivity maternityFormActivity = (BasePncFormActivity) activity;
done

2020-05-28 09:22 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +    private PncRegisterQueryProviderContract maternityRegisterQueryProvider;
done

2020-05-28 09:22 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +        maternityRegisterQueryProvider = ConfigurationInstancesHelper.newInstance(PncLibrary.getInstance().getPncConfiguration().getMaternityRegisterQueryProvider());
done

2020-05-28 09:23 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +        return R.string.maternity_register_title_name;
done

2020-05-28 09:23 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +                String sql = maternityRegisterQueryProvider.getObjectIdsQuery(filters, mainCondition);
done

2020-05-28 09:23 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +                query = maternityRegisterQueryProvider.mainSelectWhereIDsIn();
done

2020-05-28 09:24 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +            for (String sql : maternityRegisterQueryProvider.countExecuteQueries(filters, mainCondition)) {
done

2020-05-28 09:26 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/holder/PncRegisterViewHolder.java
> +        firstDotDivider = itemView.findViewById(R.id.tv_maternityRegisterListRow_firstDotDivider);
done

2020-05-28 09:27 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/interactor/BasePncRegisterActivityInteractor.java
> +    }
done

2020-05-28 09:27 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/interactor/BasePncRegisterActivityInteractor.java
> +    public void saveRegistration(List<PncEventClient> maternityEventClientList, String jsonString, RegisterParams registerParams, PncRegisterActivityContract.InteractorCallBack callBack) {
done

2020-05-28 09:28 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/interactor/PncProfileInteractor.java
> +    private void saveRegistration(@NonNull PncEventClient maternityEventClient, @NonNull String jsonString
done

2020-05-28 09:28 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/listener/LookUpTextWatcher.java
> +            BasePncFormFragment maternityFormFragment = (BasePncFormFragment) jsonFormFragment;
done

2020-05-28 09:29 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/model/PncProfileOverviewFragmentModel.java
> +                });
done

2020-05-28 09:30 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/model/PncRegisterActivityModel.java
> +        List<PncEventClient> maternityEventClientList = new ArrayList<>();
done

2020-05-28 09:31 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/pojo/PncMetadata.java
> +    private String maternityRegistrationFormName;
done

2020-05-28 09:32 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/BasePncRegisterActivityPresenter.java
> +        }
done

2020-05-28 09:34 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +            }
done

2020-05-28 09:35 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +            }
done

2020-05-28 09:40 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +            PncEventClient maternityEventClient = processRegistration(jsonString, registerParams.getFormTag());
done

2020-05-28 09:40 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileActivityPresenter.java
> +        PncEventClient maternityEventClient = PncJsonFormUtils.processMaternityRegistrationForm(jsonString, formTag);
done

2020-05-28 09:42 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncProfileOverviewFragmentPresenter.java
> +    private PncProfileOverviewFragmentModel model;
done

2020-05-28 09:44 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/presenter/PncRegisterFragmentPresenter.java
> +        getView().initializeQueryParams("ec_client", null, null);
done

2020-05-28 09:45 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/processor/PncMiniClientProcessorForJava.java
> +            eventTypes.add(PncConstants.EventTypeConstants.MATERNITY_CLOSE);
done

2020-05-28 09:47 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/processor/PncMiniClientProcessorForJava.java
> +        }
updated for now

2020-05-28 09:48 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/provider/PncRegisterProvider.java
> +    private final LayoutInflater inflater;
done

2020-05-28 09:49 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncDetailsRepository.java
> +    public ContentValues createValuesFor(@NonNull PncBaseDetails maternityDetails) {
done

2020-05-28 09:50 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncDetailsRepository.java
> +    public boolean saveOrUpdate(@NonNull PncBaseDetails maternityDetails) {
done

2020-05-28 09:50 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncDetailsRepository.java
> +    public PncBaseDetails findOne(@NonNull PncBaseDetails maternityDetails) {
done

2020-05-28 09:53 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncOutcomeDetailsRepository.java
> +public class PncOutcomeDetailsRepository extends PncDetailsRepository {
done

2020-05-28 10:24 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncOutcomeFormRepository.java
> +public class PncOutcomeFormRepository extends BaseRepository implements PncOutcomeFormDao {
done

2020-05-28 10:25 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncRegistrationDetailsRepository.java
> +public class PncRegistrationDetailsRepository extends PncDetailsRepository {
done

2020-05-28 10:26 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/FilePath.java
> +        String MATERNITY_VISIT_ROW = "maternity-visit-row.yml";
done

2020-05-28 10:29 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncConstants.java
> +        String MATERNITY = "maternity";
done

2020-05-28 10:29 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncDbConstants.java
> +        }
done

2020-05-28 10:30 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncDbConstants.java
> +        String MATERNITY_OUTCOME_FORM = "maternity_outcome_form";
removed due to unused

2020-05-28 10:31 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncEventUtils.java
> +    public PncEventUtils(AppExecutors appExecutors) {
file removed due to unused.

2020-05-28 10:32 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncEventUtils.java
> +            maternityLibrary.getClientProcessorForJava().processClient(maternityLibrary.getEcSyncHelper().getEvents(lastSyncDate, BaseRepository.TYPE_Unprocessed));
file removed due to unused.

2020-05-28 10:32 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncJsonFormUtils.java
> +
done

2020-05-28 10:35 UTC, syedowaisali90 commented on opensrp-pnc/src/main/res/layout/dosage_and_duration_layout.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2020-05-28 10:40 UTC, syedowaisali90 commented on opensrp-pnc/src/main/res/drawable/outcome_btn_overview_bg.xml
> +<?xml version="1.0" encoding="utf-8"?>
removed

2020-05-28 10:42 UTC, syedowaisali90 commented on opensrp-pnc/src/main/res/drawable/maternity_outcome_bg.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
rename.

2020-05-28 10:42 UTC, syedowaisali90 commented on opensrp-pnc/src/main/res/drawable/maternity_btn_overview_normal.xml
> +<shape
rename

2020-05-28 10:42 UTC, syedowaisali90 commented on opensrp-pnc/src/main/res/drawable/maternity_btn_overview_clicked.xml
> +    xmlns:android="http://schemas.android.com/apk/res/android"
rename

2020-05-28 10:44 UTC, syedowaisali90 commented on opensrp-pnc/src/main/res/drawable/diagnose_treat_bg.xml
> +<selector xmlns:android="http://schemas.android.com/apk/res/android">
removed.

2020-05-28 10:45 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/PncProfileOverviewFragment.java
> +        View view =  inflater.inflate(R.layout.maternity_fragment_profile_overview, container, false);
done

2020-05-28 11:12 UTC, syedowaisali90 commented on opensrp-pnc/src/main/assets/rule/maternity/outcome_relevance_rules.yml
> +---
done

2020-05-28 13:15 UTC, bennsimon submitted a review, later dismissed

2020-05-28 13:15 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncRegistrationDetailsRepository.java
> +public class PncRegistrationDetailsRepository extends PncDetailsRepository {
cool

2020-05-29 07:25 UTC, bennsimon approved these changes

2020-06-02 07:29 UTC, merged