Issue11/pnc recurring visit
OpenSRP/opensrp-client-pnc pull request #14
Opened 2020-06-29 13:46 UTC by syedowaisali90

Hi @bennsimon I have created this PR for review. Could you look into that

2020-07-01 05:50 UTC, bennsimon requested changes

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/build.gradle
> -}
Any reason why you removed this .... its needed for coverage reporting

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncRegisterActivity.java
> +        Map<String, String> detailMap = CoreLibrary.getInstance().context().detailsRepository().getAllDetailsForClient(baseEntityId);
This wont work for Giz we have disabled `ec_details` table. The `ec_details` table brings in performance issues, so it would be best to write a custom query to replace this.

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncRegisterActivity.java
> +        }
It would be better to loop through all the steps looking for a particular step title since order of steps can be changed

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncRegisterActivity.java
> +        }
use injectedValues here also

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +                        }
What of `overdue` or `expired`

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncChildRepository.java
> +            }
Could you look for a way this can be done on the query it self instead of looping on the results and adding count. Also 
 add an argument to pass the number of days.

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncDbConstants.java
> +            String BABY_CARE_MGMT = "baby_care_mgt";
Are all this in `Pnc Visit` table ? If not put the columns in their respective tables

2020-07-01 05:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/widgets/PncRepeatingGroupFactory.java
> +                MaterialEditText referenceEditText = views.get(0).findViewById(R.id.reference_edit_text);
Refer to the example in native forms sample app, there is already a feature in native forms for this.

2020-07-01 07:30 UTC, syedowaisali90 commented on opensrp-pnc/build.gradle
> -}
do I really need this although we have this task in the reporting task list.

2020-07-01 08:11 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncRegisterActivity.java
> +        Map<String, String> detailMap = CoreLibrary.getInstance().context().detailsRepository().getAllDetailsForClient(baseEntityId);
updated.

2020-07-01 08:21 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/activity/BasePncRegisterActivity.java
> +        }
updated

2020-07-01 08:24 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/fragment/BasePncRegisterFragment.java
> +                        }
the remaining case has been handled in issue #4

2020-07-01 09:31 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncChildRepository.java
> +            }
updated as per requirements.

2020-07-01 09:33 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncDbConstants.java
> +            String BABY_CARE_MGMT = "baby_care_mgt";
it's related to pnc_visit table

2020-07-01 09:34 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/widgets/PncRepeatingGroupFactory.java
> +                MaterialEditText referenceEditText = views.get(0).findViewById(R.id.reference_edit_text);
could i do that later?

2020-07-01 09:54 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/utils/PncDbConstants.java
> +            String BABY_CARE_MGMT = "baby_care_mgt";
Just for organization sake you should have columns in their particular table

2020-07-01 10:03 UTC, bennsimon requested changes

2020-07-01 10:03 UTC, bennsimon commented on opensrp-pnc/build.gradle
> -}
yeah you need this

2020-07-16 20:01 UTC, syedowaisali90 commented
Hi @bennsimon i have updated test could you look into that

2020-07-17 07:52 UTC, bennsimon requested changes

2020-07-17 07:52 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncChildRepository.java
> +        }
You need to close the cursor

2020-07-17 09:25 UTC, syedowaisali90 commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncChildRepository.java
> +        }
I think there is no need to close the cursor since it's managed by `try with resource` it will be closed automatically.

2020-07-17 09:39 UTC, bennsimon approved these changes

2020-07-18 06:50 UTC, bennsimon commented on opensrp-pnc/src/main/java/org/smartregister/pnc/repository/PncChildRepository.java
> +        }
rename the method to be more general, since youre passing the days

2020-07-18 18:03 UTC, merged